package core;

public enum PerkList {
		
	IronFist("Iron Fist", 0, 1, 5, new int[]{0, 2, 9, 18, 31, 46}, new String[]{"Channel your chi to unleash devastating fury! Punching attacks do 20% more damage to your opponent.", "Punching attacks now do 40% more damage and can disarm your opponent.", "Punching attacks now do 60% more damage. Unarmed Power Attacks have a chance to cripple one of your opponent's limbs.", "Punching attacks now do 80% more damage. Unarmed Power Attacks have an increased chance to cripple one of your opponent's limbs.", "Punching attacks now do double damage. Criticals in V.A.T.S. will paralyze your opponent."}),
	BigLeagues("Big Leagues", 0, 2, 5, new int[]{0, 2, 7, 15, 27, 42}, new String[]{"Swing for the fences! Do 20% more melee weapon damage.", "You now do 40% more melee weapon damage and gain a chance to disarm your opponent.", "You now do 60% more melee weapon damage and gain an increased chance to disarm your opponent.", "You now do 80% more melee weapon damage and hit all targets in front of you.", "You now do double damage with a melee weapon, and gain a chance to cripple your opponent, or grand slam their head clean off!"}),
	Armorer("Armorer", 0, 3, 4, new int[]{0, 2, 13, 25, 39}, new String[]{"Protect yourself from the dangers of the Wasteland with access to base level and Rank 1 armor mods.", "You gain access to Rank 2 armor mods", "You gain access to Rank 3 armor mods", "You gain access to Rank 4 armor mods"}),
	Blacksmith("Blacksmith", 0, 4, 3, new int[]{0, 2, 16, 29}, new String[]{"Fire up the forge and gain access to base level and Rank 1 melee weapon mods.","You gain access to Rank 2 melee weapon mods", "You gain access to Rank 3 melee weapon mods"}),
	HeavyGunner("Heavy Gunner", 0, 5, 5, new int[]{0, 2, 11, 21, 35, 47}, new String[]{"Thanks to practice and conditioning, heavy guns do 20% more damage.", "Heavy guns now do 40% more damage, and have improved hip fire accuracy.", "Heavy guns now do 60% more damage. Hip fire accuracy is increased even more.", "Heavy guns now do 80% more damage and have a chance to stagger your opponent.", "Heavy guns now do double damage."}),
	StrongBack("Strong Back", 0, 6, 5, new int[]{0, 2, 10, 20, 30, 40}, new String[]{"What are you, part pack mule? Gain +25 to carry weight", "You now have +50 to carry weight.", "When overencumberred, you can use Action Points to run.", "When overencumbered, you can fast travel. In Survival Mode, you cannot fast travel but you will not become injured by being overencumbered.", "When overencumbered, running costs 50% less action points."}),
	SteadyAim("Steady Aim", 0, 7, 3, new int[]{0, 2, 28, 49}, new String[]{"Stay on target! Hip-fire accuracy is improved when firing any gun.", "Hip-fire accuracy is improved even more when firing any gun.", "Hip fire damage is improved by 5% firing any gun."}),
	Basher("Basher", 0, 8, 4, new int[]{0, 2, 5, 14, 26}, new String[]{"Get up close and personal! Gun bashing does 25% more damage.", "Gun bashing now does 50% more damage and possibly cripples your opponent.", "Gun bashing now does 75% more damage and has an increased chance to cripple your opponent.", "Gun bashing does double damage and has an increased chance to cripple your opponent. It may also inflict a Critical Hit."}),
	Rooted("Rooted", 0, 9, 3, new int[]{0, 2, 22, 43}, new String[]{"You're part tree! While standing still, you gain +25 Damage Resistance and your melee and unarmed attacks deal 25% more damage.", "While standing still, you now gain +50 Damage Resistance and your melee and unarmed attacks deal 50% more damage.", "While standing still, you may automatically disarm enemies that use melee weapons against you."}),
	PainTrain("Pain Train", 0, 10, 3, new int[]{0, 2, 24, 50}, new String[]{"Choo Choo! All aboard! While wearing Power Armor, sprinting into enemies hurts and staggers them. (Robots and oversized enemies are immune to the stagger.)", "Sprinting into enemies while wearing Power Armor now causes severe damage and a more powerful stagger. (Robots and oversized enemies are immune to the stagger.)", "Sprinting into enemies while wearing Power Armor now causes massive damage and knocks them down. Impact landing near enemies inflicts even more damage."}),
	Pickpocket("Pick Pocket", 1, 1, 4, new int[]{0, 2, 6, 17, 31}, new String[]{"Your quick hands and sticky fingers make picking pockets 25% easier.", "Picking pockets is now 50% easier. You can place a live grenade in a person's inventory.", "Picking pockets is now 75% easier, and you can steal equipped weapons.", "Picking pockets is now twice as easy, and you can steal equipped items."}),
	Rifleman("Rifleman", 1, 2, 5, new int[]{0, 2, 9, 18, 31, 46}, new String[]{"Keep your distance long and your kill-count high. Attacks with non-automatic rifles do 20% more damage.", "Attacks with non-automatic rifles do 40% more damage and ignore 15% of a target's armor.", "Attacks with non-automatic rifles do 60% more damage and ignore 20% of a target's armor.", "Attacks with non-automatic rifles do 80% more damage and ignore 25% of a target's armor. They also have a slight chance of crippling a limb.", "Attacks with non-automatic rifles do double damage and ignore 30% of a target's armor. They also have a slightly higher chance of crippling a limb."}),
	Awareness("Awareness", 1, 3, 2, new int[]{0, 2, 14}, new String[]{"To defeat your enemies, know their weaknesses! You can view a target's specific damage resistances in V.A.T.S.", " Increases hit chance and damage in V.A.T.S by 5%."}),
	Locksmith("Locksmith", 1, 4, 4, new int[]{0, 2, 7, 18, 41}, new String[]{"Your nimble fingers allow you to pick advanced locks.", "You can pick Expert locks.", "You can pick Master locks.", "Your bobby pins never break during lockpicking."}),
	DemolitionExpert("Demolition Expert", 1, 5, 4, new int[]{0, 2, 10, 22, 34}, new String[]{"The bigger the boom, the better! Your explosives do 25% more damage, and you can craft explosives at any Chemistry Station.", "Your explosives do 50% more damage, and grenades gain a throwing arc.", "Your explosives do 75% more damage and affect a larger area.", "Your explosives now do double damage. Mines and grenades shot in V.A.T.S explode for double damage, too."}),
	NightPerson("Night Person", 1, 6, 3, new int[]{0, 2, 25, 37}, new String[]{"You are a creature of the night! Gain +2 to Intelligence and Perception between the hours of 6:00 p.m. and 6:00 a.m.", "You now have +3 to Intelligence and Perception between the hours of 6:00 p.m. and 6:00 a.m., and night vision when sneaking.", "You have 30 extra health between the hours of 6:00 p.m. and 6:00 a.m."}),
	Refractor("Refractor", 1, 7, 5, new int[]{0, 2, 11, 21, 35, 42}, new String[]{"You must be part mirror! Instantly gain +10 Energy Resistance.", "You now have +20 Energy Resistance.", "You now have +30 Energy Resistance.", "You now have +40 Energy Resistance.", "You now have +50 Energy Resistance."}),
	Sniper("Sniper", 1, 8, 3, new int[]{0, 2, 13, 26}, new String[]{"It's all about focus. You have improved control and can hold your breath longer when aiming with scopes.", "Non-automatic, scoped rifles have a chance of knocking down your target.", "Non-automatic, scoped rifles gain +25% accuracy to head shot in V.A.T.S."}),
	Penetrator("Penetrator", 1, 9, 2, new int[]{0, 2, 28}, new String[]{"There's no place to hide! In V.A.T.S. you can target an enemy's body parts that are blocked by cover, with a decrease in accuracy.", "In V.A.T.S. when you target an enemy's body parts that are blocked by cover, there is no decrease in accuracy."}),
	ConcentratedFire("Concentrated Fire", 1, 10, 3, new int[]{0, 2, 26, 50}, new String[]{"Stay Focused! In V.A.T.S. every attack on the same body part gains +10% accuracy.", "In V.A.T.S. every attack on the same body part gains +15% accuracy.", "In V.A.T.S. every attack on the same body part gains +20% accuracy and does 20% more damage."}),
	Toughness("Toughness", 2, 1, 5, new int[]{0, 2, 9, 18, 31, 46}, new String[]{"If nothing else, you can take a beating! Instantly gain +10 Damage Resistance", "You now have +20 damage resistance.", "You now have +30 damage resistance.", "You now have +40 damage resistance.", "You now have +50 damage resistance."}),
	LeadBelly("Lead Belly", 2, 2, 3, new int[]{0, 2, 8, 20}, new String[]{"Your digestive tract has adjusted to the weirdness of the Wasteland! Take less radiation from eating or drinking.", "You take even less radiation from eating or drinking.", "You take no radiation from eating or drinking."}),
	Lifegiver("Lifegiver", 2, 3, 3, new int[]{0, 2, 8, 20}, new String[]{"You embody wellness! Instantly gain +20 maximum Health.", "You instantly gain another +20 maximum Health.", "You instantly gain another +20 maximum Health, and slowly regenerate lost Health."}),
	ChemResistant("Chem Resistant", 2, 4, 2, new int[]{0, 2, 22}, new String[]{"All the rush without the hassle! You're 50% less likely to get addicted when consuming Chems", "You gain complete immunity to chem addiction."}),
	Aquaboy("Aquaboy", 2, 5, 2, new int[]{0, 2, 21}, new String[]{"Water is your ally. You no longer take radiation damage from swimming, and can breathe underwater.", "You become totally undetectable while submerged."}),
	RadResistant("Rad Resistant", 2, 6, 4, new int[]{0, 2, 13, 26, 35}, new String[]{"Exposure to the Wasteland has made you more resilient, instantly granting +10 Radiation Resistance.", "You now have +20 Radiation Resistance.", "You now have +30 Radiation Resistance.", "You now have +40 Radiation Resistance."}),
	AdamantiumSkeleton("Adamantium Skeleton", 2, 7, 3, new int[]{0, 2, 13, 26}, new String[]{"Your skeleton has been infused with indestructible metal, reducing limb damage by 30%.", "Your limb damage is now reduced by 60%.", "Your limb damage is completely eliminated."}),
	Cannibal("Cannibal", 2, 8, 3, new int[]{0, 2, 19, 38}, new String[]{"Feast on mortal flesh to heal your wounds! Eating human corpses restores Health. Each corpse for this rank heals a total of 25 health.","Eating Ghoul or Super Mutant corpses restores Health. Each corpse for this rank heals a total of 25 health.","Eating human, Ghoul or Super Mutant corpses now restores a significant amount of Health. Each corpse for this rank heals a total of 50 health."}),
	Ghoulish("Ghoulish", 2, 9, 4, new int[]{0, 2, 24, 48, 49}, new String[]{"Sure, you're still human - on the outside! Radiation now regenerates your lost Health.", "Radiation now regenerates even more of your lost Health.", "Radiation now regenerates even more of your lost Health, and some Feral Ghouls will randomly become friendly.", "Rad damage will now begin to slowly heal, restoring health in the process."}),
	SolarPowered("Solar Powered", 2, 10, 3, new int[]{0, 2, 27, 50}, new String[]{"Catch some rays! Gain +2 to Strength and Endurance between the hours of 6:00a.m. and 6:00p.m.", "Sunlight slowly heals your radiation damage", "Sunlight slowly regenerates your lost Health."}),
	CapCollector("Cap Collector", 3, 1, 3, new int[]{0, 2, 20, 41}, new String[]{"You've mastered the art of the deal! Buying and selling prices at vendors are better. (10% extra when selling, 10% off when buying)", "Buying and selling prices of vendors are now much better. (20% extra when selling, 20% off when buying)", "You can now invest a total of 500 caps to raise a store's buying capacity."}),
	LadyKiller("Lady Killer", 3, 2, 3, new int[]{0, 2, 7, 16}, new String[]{"You're charming... and dangerous. Women suffer +5% damage in combat, and are easier to persuade in dialogue.", "Women now suffer +10% damage in combat, and are even easier to persuade in dialogue. They are also easier to pacify with the Intimidation perk.", "Women now suffer +15% damage in combat, and are much easier to persuade in dialogue. They are now even easier to pacify with the Intimidation perk."}),
	LoneWanderer("Lone Wanderer", 3, 3, 4, new int[]{0, 2, 17, 40, 50}, new String[]{"Who needs friends, anyway? When adventuring without a companion, you take 15% less damage and carry weight increases by 50.", "When adventuring without a companion, you take 30% less damage and carry weight increases by 100", "When adventuring without a companion, you do 25% more damage.", "When adventuring without a companion, you have 25 more action points."}),
	AttackDog("Attack Dog", 3, 4, 4, new int[]{0, 2, 9, 25, 31}, new String[]{"Your faithful canine companion can hold an enemy, giving you a greater chance to hit them in V.A.T.S.", "When your dog holds an enemy, there's a chance he'll cripple the limb he's biting.", "When your dog holds an enemy, there's a chance he'll cause them to bleed.", "When adventuring with your dog, you take 10% less damage."}),
	AnimalFriend("Animal Friend", 3, 5, 3, new int[]{0, 2, 12, 28}, new String[]{"Commune with beasts! With your gun, aim at any animal below your level and gain a chance to pacify it.", "When you successfully pacify an animal, you can incite it to attack.", "When you successfully pacify an animal, you can give it specific commands."}),
	LocalLeader("Local Leader", 3, 6, 2, new int[]{0, 2, 14}, new String[]{"As the ruler everyone turns to, you are able to establish supply lines between your workshop settlements.", "You can build stores and workstations at workshop settlements."}),
	PartyBoy("Party Boy", 3, 7, 3, new int[]{0, 2, 15, 37}, new String[]{"Nobody has a good time like you! There's no chance you'll get addicted to alcohol.", "The effects of alcohol are doubled.", "Your Luck is increased by 3 while you're under the influence of alcohol."}),
	Inspirational("Inspirational", 3, 8, 3, new int[]{0, 2, 19, 43}, new String[]{"Because you lead by example, your companion does more damage in combat, and cannot hurt you.", "Your companion resists more damage in combat, and can't be harmed by your attacks.", "Your companion can carry more items. Increases carry weight of your companion by 25 pounds."}),
	WastelandWhisperer("Wasteland Whisperer", 3, 9, 3, new int[]{0, 2, 21, 49}, new String[]{"Master the post-apocalypse! With your gun, aim at any Wasteland creature below your level and gain a chance to pacify it.", "When you successfully pacify a creature, you can incite it to attack.", "When you successfully pacify a creature, you can give it specific commands."}),
	Intimidation("Intimidation", 3, 10, 3, new int[]{0, 2, 23, 50}, new String[]{"Time to show everyone who's boss! With your gun, aim at any human opponent below your level and gain a chance to pacify them.", "When you successfully pacify someone, you can incite them to attack.", "When you successfully pacify someone, you can give them specific commands."}),
	Vans("V.A.N.S.", 4, 1, 2, new int[]{0, 2, 36}, new String[]{"Let Vault-Tec guide you! The path to your closest quest target is displayed in V.A.T.S. Long pressing the V.A.T.S. button out of combat will result in a ghost trail on the ground showing you the pathway to quest targets. Most useful in multi-story buildings.", "Gain +2 to Perception."}),
	Medic("Medic", 4, 2, 4, new int[]{0, 2, 18, 30, 49}, new String[]{"Is there a doctor in the house? Stimpaks restore 40% of lost Health, and RadAway removes 40% of radiation.", "Stimpaks restore 60% of lost Health, and RadAway removes 60% of radiation.", "Stimpaks restore 80% of lost Health, and RadAway removes 80% of radiation", "Stimpaks and RadAway restore all lost health and radiation, and work much more quickly."}),
	GunNut("Gun Nut", 4, 3, 4, new int[]{0, 2, 13, 25, 39}, new String[]{"You gain access to base level and Rank 1 gun mods.", "You gain access to Rank 2 gun mods", "You gain access to Rank 3 gun mods.", "You gain access to Rank 4 gun mods."}),
	Hacker("Hacker", 4, 4, 4, new int[]{0, 2, 9, 21, 33}, new String[]{"Knowledge of cutting-edge computer encryption allows you to hack Advanced terminals", "You can hack Expert terminals.", "You can hack Master terminals.", "When hacking, you never get locked out of a terminal when things go wrong."}),
	Scrapper("Scrapper", 4, 5, 3, new int[]{0, 2, 23, 40}, new String[]{"Waste not, want not! You can salvage uncommon components like screws, aluminum, and copper when scrapping weapons and armor.", "You can salvage rare components like circuitry, nuclear material, and fiber optics when scrapping weapons and armor. Items with favorited components are highlighted.", "You get more from salvaging."}),
	Science("Science!", 4, 6, 4, new int[]{0, 2, 17, 28, 41}, new String[]{"Take full advantage of advanced technology with access to base level and Rank 1 high-tech mods.", "You gain access to Rank 2 high-tech mods.", "You gain access to Rank 3 high-tech mods.", "You gain access to Rank 4 high-tech mods."}),
	Chemist("Chemist", 4, 7, 4, new int[]{0, 2, 16, 32, 45}, new String[]{"Any chems you take last 50% longer. Far out.", "Any chems you take now last twice as long.", "Any chems you take now last an additional 150% longer.", "Any chems you take now last an additional 200% longer."}),
	RoboticsExpert("RoboticsExpert", 4, 8, 3, new int[]{0, 2, 19, 44}, new String[]{"Machines will always serve humans, if you have anything to say about it. Hack a robot, and gain a chance to power it on or off, or initiate a self-destruct.", "When you successfully hack a robot, you can incite it to attack.", "When you successfully hack a robot, you can give it specific commands. [Command as a companion only]"}),
	NuclearPhysicist("Nuclear Physicist", 4, 9, 3, new int[]{0, 2, 14, 26}, new String[]{"You've learned to split the atom... and command it. Radiation weapons do 50.5% more damage and Fusion Cores last an extra 25% longer.", "Radiation weapons now do double damage and Fusion Cores last an extra 50% longer.", "Fusion Cores can be ejected from Power Armor like devastating grenades and Fusion Cores last twice as long."}),
	NerdRage("Nerd Rage!", 4, 10, 3, new int[]{0, 2, 31, 50}, new String[]{"Genius. Is. ANGRY! When your Health drops below 20%, time slows and you gain +20 Damage resistance and do 20% more damage while the effect lasts.", "You now gain 30 more Damage Resistance and do 30% more damage while Nerd Rage is in effect.", "You now gain 40 more Damage Resistance and do 40% more damage while Nerd Rage is in effect. Kills you make while enraged restore some lost Health."}),
	Gunslinger("Gunslinger", 5, 1, 5, new int[]{0, 2, 7, 15, 27, 42}, new String[]{"Channel the spirit of the old west! Non-automatic pistols do 20% more damage.", "Non-automatic pistols now do 40% more damage and have increased range.", "Non-automatic pistols now do 60% more damage and range is increased even further.", "Non-automatic pistols now do 80% more damage and their attacks can disarm opponents.", "Non-automatic pistols now do double damage. Their attacks have a much better chance to disarm opponents, and may even cripple a limb."}),
	Commando("Commando", 5, 2, 5, new int[]{0, 2, 11, 21, 35, 49}, new String[]{"Rigorous combat training means automatic weapons do 20% more damage", "Attacks with automatic weapons do 40% more damage, with improved hip fire accuracy.", "Attacks with automatic weapons do 60% more damage. Hip fire accuracy is improved even more.", "Attacks with automatic weapons do 80% more damage and gain a chance to stagger opponents.", "Your automatic weapons now do double damage and have a greater chance to stagger opponents."}),
	Sneak("Sneak", 5, 3, 5, new int[]{0, 2, 5, 12, 23, 38}, new String[]{"You are now 30% harder to detect while sneaking, and no longer trigger floor-based traps.", "You are now 30% harder to detect while sneaking, and no longer trigger floor-based traps.", "You are now 40% harder to detect while sneaking, and no longer trigger enemy mines.", "You are now 50% harder to detect while sneaking, and running no longer adversely affects stealth.", "Engaging stealth causes distant enemies to lose you."}),
	MisterSandman("Mister Sandman", 5, 4, 3, new int[]{0, 2, 17, 30}, new String[]{"As an agent of death, you can instantly kill a sleeping person. Your silenced weapons do an additional 15% sneak attack damage.", "Your silenced weapons do an additional 30% sneak attack damage.", "Your silenced weapons now do 50% more sneak attack damage."}),
	ActionBoy("Action Boy", 5, 5, 3, new int[]{0, 2, 18, 38}, new String[]{"There's no time to waste! Action Points regenerate 25% faster.", "Your Action Points now regenerate 50% faster.", "Your Action Points now regenerate 75% faster."}),
	MovingTarget("Moving Target", 5, 6, 3, new int[]{0, 2, 24, 44}, new String[]{"They can't hurt what they can't hit! Get 25+ Damage Resistance and 25+ Energy Resistance when you're sprinting.", "You now get +50 Damage Resistance and +50 Energy Resistance when you're sprinting.", "Sprinting costs 50% fewer Action Points."}),
	Ninja("Ninja", 5, 7, 3, new int[]{0, 2, 16, 33}, new String[]{"Trained as a shadow warrior, your ranged sneak attacks do 2.5x normal damage and your melee attacks do 4x normal damage.", "Your ranged sneak attacks do 3x normal damage and your melee sneak attacks do 5x normal damage.", "Your ranged sneak attacks do 3.5x normal damage and your melee sneak attacks do 10x normal damage."}),
	QuickHands("Quick Hands", 5, 8, 3, new int[]{0, 2, 28, 40}, new String[]{"In combat, there's no time to hesitate. You can reload all guns faster.", "Reloading guns costs no Action Points in V.A.T.S.", "You gain 10 additional Action Points."}),
	Blitz("Blitz", 5, 9, 2, new int[]{0, 2, 29}, new String[]{"Find the gap and make the tackle! V.A.T.S. melee distance is increased significantly.", "V.A.T.S. melee distance is increased even more, and the farther the Blitz distance, the greater the damage."}),
	GunFu("Gun Fu", 5, 10, 3, new int[]{0, 2, 26, 50}, new String[]{"You've learned to apply ancient martial arts to gunplay! Do 25% more damage to your second V.A.T.S. target and beyond.", "In V.A.T.S. you do 50% more damage to your third target and beyond.", "In V.A.T.S. you instantly do a Critical Hit against your fourth target and beyond."}),
	FortuneFinder("Fortune Finder", 6, 1, 4, new int[]{0, 2, 5, 25, 40}, new String[]{"You find more bottle caps in containers.", "You find even more bottle caps in containers.", "You find even more bottle caps in containers.", "You find even more bottle caps in containers, and there is a chance of enemies exploding into a shower of caps when you kill them."}),
	Scrounger("Scrounger", 6, 2, 4, new int[]{0, 2, 7, 24, 37}, new String[]{"You find more ammunition in containers.", "You find even more ammunition in containers.", "You find even more ammunition in containers.", "There is a chance to gain ammo when firing the last round in your clip."}),
	BloodyMess("Bloody Mess", 6, 3, 4, new int[]{0, 2, 9, 31, 47}, new String[]{"+5% bonus damage means enemies will sometimes explode into a gory red paste. Watch out for flying eyeballs!", "You now inflict +10% damage in combat.", "You now inflict +15% damage in combat.", "When an enemy explodes, nearby enemies may suffer the same fate."}),
	MysteriousStranger("Mysterious Stranger", 6, 4, 4, new int[]{0, 2, 22, 41, 49}, new String[]{"Who is he? Why does he help? Who cares! The Mysterious Stranger will appear occasionally in V.A.T.S. to lend a hand, with deadly efficiency...", "The Mysterious Stranger appears more often in V.A.T.S.", "The Mysterious Stranger appears more often in V.A.T.S. When he kills an opponent, there is a chance your Critical meter gets filled.", "The Mysterious Stranger appears more often in V.A.T.S. When he kills an opponent, there is a high chance your Critical meter gets filled."}),
	IdiotSavant("Idiot Savant", 6, 5, 3, new int[]{0, 2, 11, 31}, new String[]{"You're not stupid! Just... different. Randomly receive 3x XP from any action, and the lower your Intelligence, the greater the chance.", "You now randomly receive 5x XP from any action. The lower your Intelligence, the greater the chance.", "Randomly receiving bonus XP from any action may trigger 5x XP for all kills for a short period of time. The lower your Intelligence, the greater the chance."}),
	BetterCriticals("Better Criticals", 6, 6, 3, new int[]{0, 2, 15, 40}, new String[]{"Advanced training for enhanced combat effectiveness! Criticals do 50% more extra damage.", "Your criticals now do twice as much extra damage.", "Your criticals now do 2.5x as much extra damage."}),
	CriticalBanker("Critical Banker", 6, 7, 4, new int[]{0, 2, 17, 43, 50}, new String[]{"You're a patient battlefield tactician, and can save a Critical Hit, to be used in V.A.T.S. when you need it most.", "You can now save 2 Critical Hits, to be used in V.A.T.S. when you need them the most.", "You can now save 3 Critical Hits, to be used in V.A.T.S. when you need them the most. Banking a Critical has a chance to save an additional Critical.", "You can now save 4 Critical Hits, to be used in V.A.T.S. when you need them the most."}),
	GrimReapersSprint("Grim Reaper's Sprint", 6, 8, 3, new int[]{0, 2, 19, 46}, new String[]{"Death becomes you! Any kill in V.A.T.S. has a 15% chance to restore all Action Points.", "Any kill in V.A.T.S. now has a 25% chance to restore all Action Points.", "Any kill in V.A.T.S. has a 35% chance to restore all Action Points and refill your Critical meter."}),
	FourLeafClover("Four Leaf Clover", 6, 9, 4, new int[]{0, 2, 13, 32, 48}, new String[]{"Feeling Lucky? You should! Each hit in V.A.T.S. has a chance of filling your Critical meter.", "Each hit in V.A.T.S. now has an even better chance of filling your Critical meter.", "Each hit in V.A.T.S. now has a very good chance of filling your Critical meter.", "Each hit in V.A.T.S. now has an excellent chance of filling your Critical meter."}),
	Ricochet("Ricochet", 6, 10, 3, new int[]{0, 2, 29, 50}, new String[]{"What goes around comes around! Any enemy's ranged attacks will sometimes ricochet back and instantly kill them. The closer you are to death, the higher the chance.", "There's an increased chance that an enemy's shot will ricochet back and kill them.", "When an enemy's shot ricochets back and kills them, there is a chance your Critical meter gets filled."});
	
	private String name;
	private int statType, statReq, ranks;
	private int[] levelReq;
	private String[] description;
	
	PerkList(String name, int statType, int statReq, int ranks, int[] levelReq, String[] description){
		this.name = name;
		this.statType = statType;
		this.statReq = statReq;
		this.ranks = ranks;
		this.levelReq = levelReq;
		this.description = description;
	}

	public String getName() {
		return name;
	}

	public int getStatType() {
		return statType;
	}

	public int getStatReq() {
		return statReq;
	}

	public int getRanks() {
		return ranks;
	}

	public int getLevelReq(int i) {
		return levelReq[i];
	}

	public String getDescription(int i) {
		return description[i];
	}

}
